test_win:
  hosts:
    app:
      ansible_host: 10.0.0.48
test_lin:
  hosts:
    test:
      ansible_host: 192.168.1.100
    monitoring-server:
      ansible_host: 192.168.1.102
    monitoring-host1:
      ansible_host: 192.168.1.103 
