test_win:
  hosts:
    10.0.0.48:
      ansible_host: 10.0.0.48
      ansible_user: user
      ansible_password: user
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
test_lin:
  hosts:
    test_ubuntu:
      ansible_host: 10.0.0.30
      ansible_user: test
      ansible_ssh_private_key_file: /home/eremeevda/.ssh/id_rsa
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_pass: test
